### ISSUE TITLE
"Remember Upto" field got reset to 100 from 500 and I lost over 300 closed tabs

### ISSUE THREAD

**Issue by vkshah2** [jacobSingh/tabwrangler#121] opened 2017-04-02 19:34 UTC

**Comment by ssorallen** [comment] 2017-04-02 20:47
I'm sorry Tab Wrangler lost your tabs. Can you give any more info about when or how it happened? I want to find the cause so I can ensure it's fixed in the next version.

Which version of TW are you using (see the "About" tab)?

Was the pop up open when this happened?

Any other info you can remember?

**Comment by vkshah2** [comment] 2017-04-02 20:59
v5.0.1


I'm not sure when exactly I lost the tabs. Hadn't worked on  my laptop for a couple of days apart from opening a few tabs maybe.Today, sometime into browsing I saw the 100 and checked the list. I have my recent 100 tabs but lost everything before that. I had around 300-350 tabs wrangled. 


Also, I had set a keyboard shortcut which also got reset. Actually this is what made me realise the lost tabs. So the problem could have occured earlier. 


Not sure what else I can share. I'll go through my web history once to recover the tabs since most of them were from last week, so its not much of a hassle. Just thought of reporting it, since this cannot happen by user error. 


Let me know if you wanna remote.



From: Ross Allen

Sent: Monday, 3 April, 2:17 a.m.

Subject: Re: [jacobSingh/tabwrangler] "Remember Upto" field got reset to 100 from 500 and I lost over 300 closed tabs (#121)

To: jacobSingh/tabwrangler

Cc: Vinit Shah, Author



I'm sorry Tab Wrangler lost your tabs. Can you give any more info about when or how it happened? I want to find the cause so I can ensure it's fixed in the next version.


Which version of TW are you using (see the "About" tab)?


Was the pop up open when this happened?


Any other info you can remember?

**Comment by ssorallen** [comment] 2017-04-02 23:48
Thanks for the details. If the keyboard shortcut was lost, it sounds like your settings were lost and reverted to the defaults. I haven't yet seen this problem, but I will see if I can reproduce it.

**Comment by ssorallen** [comment] 2017-05-22 08:06
I haven't been able to reproduce this while working on Tab Wrangler. If you have more details on the steps to reproduce this, I am happy to take a look. Please reopen if you have more details.

**Closed by ssorallen** 2017-05-22 08:06 UTC
