### ISSUE TITLE
is it possible to stop recording time when turn to other apps ? 

### ISSUE THREAD

**Issue by BigAN** [jacobSingh/tabwrangler#149] opened 2017-08-12 08:45 UTC
is it possible to stop recording time when turn to other apps ? 

for that, sometimes i need to turn to pycharm  to code, but when i come back, tabs are all closed as i set waiting minutes to 10 minutes. 

but i do not want this happen , i think ,the scene should be  when i look at the chrome, time record start, or time record stop.

**Comment by BigAN** [comment] 2017-08-12 08:46
thanks for your great work

**Comment by ssorallen** [comment] 2017-08-12 17:53
Yes I think this would be a great addition. This is tracked in #5 and would require a new permission.

Thanks for the suggestion. I'm closing this as a duplicate of #5.

**Closed by ssorallen** 2017-08-12 17:53 UTC
