### ISSUE TITLE
Only scroll list of tabs

### ISSUE THREAD

**Issue by eorroe** [jacobSingh/tabwrangler#133] opened 2017-05-30 16:46 UTC
Hey I notice the whole UI scrolls, I'd love if the search bar and other Tabs stayed put, and only the tabs scroll.

The UI in the image below should stay put:

![image](https://cloud.githubusercontent.com/assets/6982605/26594507/dda27e34-4535-11e7-9cff-ec77ccdc5218.png)

**Comment by ssorallen** [comment] 2017-05-30 17:11
The action bar should stick to the top when you scroll in the Corral Tab. Is that not the case?

**Comment by eorroe** [comment] 2017-05-30 19:40
I only see the Select All, and Sort buttons being sticky. But I'm saying to instead just make the list container scrollable while everything else stays put. Instead of the whole UI scrolling and keeping the action bar sticky, why not just the tabs scroll?

**Comment by ssorallen** [comment] 2017-05-30 20:02
> I only see the Select All, and Sort buttons being sticky.

Right right, that was my intention. Because there is no longer an 'X' button for each row, I wanted to make sure you could act on rows regardless of where you had scrolled in the list.

The tabs don't act on the scrollable list, so they don't need to stick when scrolling.

**Comment by eorroe** [comment] 2017-05-30 22:55
I just inspected the Popup. Basically, I'm asking for your `corralTable` to be the only scrollable part. Where everything else stays the same.

**Comment by ssorallen** [comment] 2017-05-30 23:12
@eorroe I understand, but I'm saying it's working as I intended already! What are you trying to do once you've scrolled down the page? Let's figure out what part of the workflow is incorrect.

**Comment by eorroe** [comment] 2017-05-30 23:19
So let's say I have over 100+ tabs on TabWrangler, it's not much of a pain to scroll back up. But it does reduce some friction to just keep everything in view while the tabs are scrollable. Plus I believe if I'm not mistaking, it will reduce the code for what's keeping the Action Bar showing after scroll.

**Comment by ssorallen** [comment] 2017-06-16 15:31
Only the controls that affect the list are meant to scroll; it's currently working as designed. Check out the Bootstrap [Components page](https://getbootstrap.com/components/) as an example. Only controls affecting the current page scroll with you, global navigation stays statically positioned at the top.

I'm closing this for now, but let's chat again if the interaction continues to feel strange or inhibit being able to use the extension.

**Closed by ssorallen** 2017-06-16 15:31 UTC
