### ISSUE TITLE
Browser restart undoes closing of tabs in tab corral

### ISSUE THREAD

**Issue by Troetelbiertje** [jacobSingh/tabwrangler#84] opened 2014-08-15 09:31 UTC
All the pages that I close in the Tab Corral reappear when I restart the browser. 

Chrome 37.0.2062.76 beta-m
Windows 7

**Comment by ChrisNineNineEight** [comment] 2015-01-18 14:28
Same here.

**Comment by ssorallen** [comment] 2017-02-10 04:53
Closing as duplicate of #79.

**Closed by ssorallen** 2017-02-10 04:53 UTC
